# Base URL to work with github pages
baseurl: /Chart.js

# Collections of files
collections:
  doc-parts:
    output: false
  doc-parts-v2:
    output: false

markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "tables"]